load("//macros:mobile_library.bzl", "mobile_library")

mobile_library(
    name = "test-paths",
    srcs = [
        "Source/TestPaths.cpp",
    ],
    hdrs = [
        "Include/TestPaths/TestPaths.hpp",
    ],
    visibility = ["//visibility:public"],
    testonly = True,
)
