load("//macros:mobile_library.bzl", "mobile_library")

mobile_library(
    name = "paths",
    srcs = [
        "Source/Paths.cpp",
    ],
    hdrs = [
        "Include/Paths/Paths.hpp",
    ],
    visibility = ["//visibility:public"],
)
