filegroup(
    name = "GoogleTestsIosHelper",
    srcs = [
        "GoogleTests.mm",
        "gtest-internal-inl.h",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "GoogleTestsSwiftIosHelper",
    srcs = [
        "GoogleTestBridge.swift",
    ],
    visibility = ["//visibility:public"],
)
