def _host_platform_repo_impl(rctx):
    # Use Haswell by default on Intel Linux
    if rctx.os.name.startswith("linux") and rctx.os.arch in ["amd64", "x86_64", "x64"]:
        rctx.file("BUILD.bazel", """
# DO NOT EDIT: autogenerated BUILD file
alias( name = "host", actual = "@playground//platforms/linux:haswell_x86_64" )
alias( name = "host_for_crossbuild", actual = "@playground//platforms/linux:x86_64" )
        """)
    elif rctx.os.name.startswith("linux") and rctx.os.arch in ["aarch64", "arm64"]:
        rctx.file("BUILD.bazel", """
# DO NOT EDIT: autogenerated BUILD file
alias( name = "host", actual = "@playground//platforms/linux:arm64" )
alias( name = "host_for_crossbuild", actual = "@playground//platforms/linux:arm64" )
        """)
    elif rctx.os.name.startswith("darwin") and rctx.os.arch == "x86_64":
        rctx.file("BUILD.bazel", """
# DO NOT EDIT: autogenerated BUILD file
alias( name = "host", actual = "@playground//platforms/macos:x86_64" )
alias( name = "host_for_crossbuild", actual = "@playground//platforms/macos:x86_64" )
        """)
    elif rctx.os.name.startswith("darwin") and rctx.os.arch == "arm64":
        rctx.file("BUILD.bazel", """
# DO NOT EDIT: autogenerated BUILD file
alias( name = "host", actual = "@playground//platforms/macos:arm64" )
alias( name = "host_for_crossbuild", actual = "@playground//platforms/macos:arm64" )
        """)
    else:
        # Simply use whatever platforms module detected
        rctx.file("BUILD.bazel", """
# DO NOT EDIT: autogenerated BUILD file
alias( name = "host", actual = "@platforms//host:host" )
alias( name = "host_for_crossbuild", actual = "@platforms//host:host" )
        """)


host_platform_repo = repository_rule(
    implementation = _host_platform_repo_impl,
    local = True,
)

def _host_platform_impl(module_ctx):
    host_platform_repo(name = "host_platform")

    # module_ctx.extension_metadata has the paramater `reproducible` as of Bazel 7.1.0. We can't
    # test for it directly and would ideally use bazel_features to check for it, but adding a
    # dependency on it would require complicating the WORKSPACE setup. Thus, test for it by
    # checking the availability of another feature introduced in 7.1.0.
    if hasattr(module_ctx, "extension_metadata") and hasattr(module_ctx, "watch"):
        return module_ctx.extension_metadata(reproducible = True)
    else:
        return None

host_platform = module_extension(
    implementation = _host_platform_impl,
)
