load("//macros:constants.bzl", "TAG_STARLARK")
load(":flatten.bzl", "flatten_test_suite")

flatten_test_suite(
    name = "flatten_test",
)

test_suite(
    name = "starlark",
    tags = [TAG_STARLARK],
)
