#!/bin/bash

echo "Generating ios-targets.bzl..."

test_targets=$(bazel query 'kind("ios_unit_test", //...)')
app_targets=$(bazel query 'kind("ios_application", //...)')

{
  echo "# This file is auto-generated by xcode/generate_ios_targets_bzl.sh"
  echo "# Do not edit this file directly."
  echo ""
  echo "IOS_TEST_TARGETS = ["
  for target in $test_targets; do
    echo "    \"$target\","
  done
  echo "]"
  echo ""
  echo "IOS_APP_TARGETS = ["
  for target in $app_targets; do
    echo "    \"$target\","
  done
  echo "]"
} > ios-targets.bzl
