# This file is auto-generated by xcode/generate_ios_targets_bzl.sh
# Do not edit this file directly.

IOS_TEST_TARGETS = [
    "//main:hello-test-ios",
    "//main:hello-world-test-default-ios",
    "//main:hello-world-test-file-ios",
    "//main:hello-world-test-non-default-ios",
]

IOS_APP_TARGETS = [
    "//main:hello-world-ios",
    "//test-support/ios-test/GoogleTestHost:GoogleTestHost",
]
