#!/bin/bash

bazel_real="$BAZEL_REAL"
bazelrc_lines=()

if [[ $OSTYPE == darwin* ]]; then
    xcode_path=$(xcode-select -p)
    xcode_version=$(xcodebuild -version | tail -1 | cut -d " " -f3)
    xcode_build_number=$(/usr/bin/xcodebuild -version 2>/dev/null | tail -1 | cut -d " " -f3)

    bazelrc_lines+=("startup --host_jvm_args=-Xdock:name=$xcode_path")
    bazelrc_lines+=("build --xcode_version=$xcode_version")
    bazelrc_lines+=("build --repo_env=XCODE_VERSION=$xcode_version")
    bazelrc_lines+=("build --repo_env=DEVELOPER_DIR=$xcode_path")
    bazelrc_lines+=("common --test_env=DEVELOPER_DIR=$xcode_path")
elif [[ $OSTYPE == linux* ]]; then
    # Note:
    # Bazel hashes compiler based on path, which makes it hit cache between different versions of clang
    # compilers installed in different dockers. To avoid that, we create a symlink with the version in the name.
    # For example: /tmp/clang-20.1.8.
    # Long-term, we should migrate to using toolchains.
    #               (2025-10-10) (Nenad Mikša)

    clang_version=$(clang --version | head -n1 | sed 's/.*version \([^ ]*\).*/\1/')
    clang_path=$(which clang)
    ln -sf $clang_path /tmp/clang-$clang_version
    bazelrc_lines+=("common --action_env=CC=/tmp/clang-$clang_version")
fi

printf '%s\n' "${bazelrc_lines[@]}" > automatic.bazelrc

exec "$bazel_real" "$@"
