#!/bin/bash

bazel_real="$BAZEL_REAL"
bazelrc_lines=()

quote_bazelrc_value() {
    local value="$1"
    value=${value//\\/\\\\}
    value=${value//\"/\\\"}
    printf '"%s"' "$value"
}

if [[ $OSTYPE == darwin* ]]; then
    xcode_path=$(xcode-select -p)
    xcode_version=$(xcodebuild -version | tail -1 | cut -d " " -f3)

    bazelrc_lines+=("build:ios --xcode_version=$xcode_version")
    bazelrc_lines+=("build:ios --repo_env=XCODE_VERSION=$xcode_version")
    bazelrc_lines+=("build:ios --repo_env=DEVELOPER_DIR=$(quote_bazelrc_value "$xcode_path")")
    bazelrc_lines+=("common:ios --test_env=DEVELOPER_DIR=$(quote_bazelrc_value "$xcode_path")")
fi

printf '%s\n' "${bazelrc_lines[@]}" > automatic.bazelrc

exec "$bazel_real" "$@"
