filegroup(
    name = "GoogleTestsSwiftIosLoader",
    srcs = [
        "GoogleTestLoader.swift",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "GoogleTestInvokerHeader",
    srcs = [
        "GoogleTestInvoker.hpp",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "GoogleTestInvokerSource",
    srcs = [
        "GoogleTestInvoker.cpp",
    ],
    visibility = ["//visibility:public"],
)

