filegroup(
    name = "GoogleTestsSwiftIosLoader",
    srcs = [
        "GoogleTestLoader.swift",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "GoogleTestSwiftModuleMap",
    srcs = [
        "module.modulemap",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "GoogleTestSwiftIosBridgeHeader",
    srcs = [
        "SwiftCxxBridge.hpp"
    ],
    visibility = ["//visibility:public"],
)
